# "events" is a map between Github events and rules.
# possible event names can be seen at https://docs.github.com/en/actions/reference/events-that-trigger-workflows
events:
  # 'pull_request' is the Github event name.
  # '&pull_request' is a YAML anchor
  pull_request:
    - trustAnyone: false
      paths:
      	disallowed:
          - ".github/**"
          - ".github/protected-workflows.yml" # <-- Exteremly important. Only certain users should be able to change this file.
    
    # Authorize "repo-owner" regardless of what paths were changed.
    - trustedUserNames:
        - "GirishMedishetty"

  push:
    - trustAnyone: false
      paths:
      	disallowed:
          - ".github/**"
          - ".github/protected-workflows.yml" # <-- Exteremly important. Only certain users should be able to change this file.
    
    # Authorize "repo-owner" regardless of what paths were changed...
    - trustedUserNames:
        - "GirishMedishetty"

anyEvent:
  trustAnyone: false
  trustCollaborators: false
  trustedUserNames: []
